### ISSUE TITLE
Issues Related flutter_localizations in template

### ISSUE THREAD

**Issue by Lakhankumawat** [hasancse91/flutter_getx_template#28]
## 1. I ran `pub get` many times but the issue in files due to localizations remains
![issues](https://user-images.githubusercontent.com/55774240/151990133-38deb4a4-2b2d-4b61-9832-da4843d3ab9b.png)

## 2. Instead of all localizations i tried to run the main_dev but it could not make the app `running gradle assembledebug infinitely`
![issue2](https://user-images.githubusercontent.com/55774240/151990426-9f6e0518-d90a-47fc-8b8a-cf5a5e1d74d8.png)

```
F:\Github Apps\flutter_getx_template>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.434], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.63.2)
[√] Connected device (3 available)

• No issues found!
```

**Comment by AliAkberAakash** [comment]
Try deleting the generated localization files and build again. This should fix the localization errors.

**Comment by Lakhankumawat** [comment]
## For any newcomer out there 
# File-> Invalidate Caches  & Restart 
![Screenshot 2022-02-01 221110](https://user-images.githubusercontent.com/55774240/152011269-9c614354-0f07-460d-a228-36dc956b2451.png)
