### ISSUE TITLE
Refresh Token 

### ISSUE THREAD

**Issue by Parvez6084** [hasancse91/flutter_getx_template#33]
In this Project How to use the Refresh token

**Comment by Parvez6084** [comment]
I Solved It

**Comment by taftazaniadi** [comment]
How to use it?

Can you explained to me?

**Comment by Parvez6084** [comment]
Thank you for your response. I already solved the problem.

**Comment by taftazaniadi** [comment]
I'm still confused for using this template for my project, can you explained to me for how this template work?

**Comment by Parvez6084** [comment]
Its working fantastic, I already done 2 project.

**Comment by taftazaniadi** [comment]
Can i see your project @Parvez6084 ?
